//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKAKO_ERP_3LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMMF
    {
        public string CUSTOMER_CODE { get; set; }
        public string REP_CODE { get; set; }
        public string ACCOUNT_CODE { get; set; }
        public string CUSTOMER_CLASS { get; set; }
        public string EMAIL { get; set; }
        public string EMAIL2 { get; set; }
        public string CUSTOMER_NAME1 { get; set; }
        public string CUSTOMER_NAME2 { get; set; }
        public string NATIONAL_NO { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string TEL_NO { get; set; }
        public string FAX_NO { get; set; }
        public string WEBSITE { get; set; }
        public string CERTIFICATION { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string INPUT_PERSON { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFY_PERSON { get; set; }
        public Nullable<System.DateTime> BEGIN_DATE { get; set; }
        public Nullable<System.DateTime> FINISH_DATE { get; set; }
        public string MEMO { get; set; }
        public string ATTN1 { get; set; }
        public string ATTN2 { get; set; }
        public string MOBILE1 { get; set; }
        public string MOBILE2 { get; set; }
        public string SHORT_CODE { get; set; }
        public Nullable<double> AUTO_ORDER_NO { get; set; }
        public string TAX_ID { get; set; }
        public string SETTLEMENT { get; set; }
        public string PAYMENT { get; set; }
        public string CURRENCY { get; set; }
        public string INVOICE_FORMAT { get; set; }
        public Nullable<decimal> DELIVERY_TIME { get; set; }
        public Nullable<decimal> TVC_DELIVERY_TIME { get; set; }
        public Nullable<decimal> LEAD_TIME_S { get; set; }
        public Nullable<decimal> SUPPLIER_RATE { get; set; }
        public Nullable<decimal> EVALUE_ABILITY { get; set; }
        public string Payable_ACC { get; set; }
        public string Receivable_ACC { get; set; }
    }
}
