//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKAKO_ERP_3LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESTINATIONMF
    {
        public string DESTINATION_ID { get; set; }
    }
}
