//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKAKO_ERP_3LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTMF
    {
        public string ITEM_CODE { get; set; }
        public string ITEM_NAME { get; set; }
        public string ITEM_NAME_E { get; set; }
        public string ITEM_NAME_V { get; set; }
        public string ITEM_CLASSIFY { get; set; }
        public string UNIT_ITEM { get; set; }
        public string GROUP_FLAG { get; set; }
        public string PRO_CLASS { get; set; }
        public string SPREAD_FLAG { get; set; }
        public string OBJECT_CODE { get; set; }
        public string INTERNAL_CODE { get; set; }
        public string MODEL { get; set; }
        public string PRODUCTMODEL { get; set; }
        public string SHELF_CODE { get; set; }
        public string CUSTOMER { get; set; }
        public string SUPPLIER { get; set; }
        public string ROUTE { get; set; }
        public Nullable<decimal> MATERIAL_PRICE { get; set; }
        public string M_PRICE_UNIT { get; set; }
        public Nullable<decimal> SEMI_F_PRICE { get; set; }
        public string SF_PRICE_UNIT { get; set; }
        public Nullable<decimal> SALE_PRICE { get; set; }
        public string S_PRICE_UNIT { get; set; }
        public Nullable<short> LEAD_TIME { get; set; }
        public Nullable<decimal> LOT_SIZE { get; set; }
        public Nullable<decimal> PRODUCT_DAY { get; set; }
        public Nullable<decimal> SAFETY_STOCK { get; set; }
        public Nullable<decimal> LOSS { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public string WEIGHT_UNIT { get; set; }
        public string STOCK_OUT_FLAG { get; set; }
        public string BOX_TYPE { get; set; }
        public Nullable<decimal> BOX_QUANTITY { get; set; }
        public string BOX_SIZE { get; set; }
        public Nullable<decimal> BOX_WEIGHT { get; set; }
        public Nullable<bool> QA_CHECK { get; set; }
        public string MEMO { get; set; }
        public Nullable<System.DateTime> FIRST_ORDER { get; set; }
        public Nullable<System.DateTime> LAST_ORDER { get; set; }
        public Nullable<System.DateTime> LAST_PRODUCT { get; set; }
        public Nullable<System.DateTime> LAST_SHIPPING { get; set; }
        public Nullable<System.DateTime> LAST_PO { get; set; }
        public Nullable<System.DateTime> LAST_STOCK_IN { get; set; }
        public Nullable<decimal> TOTAL_ORDER { get; set; }
        public Nullable<decimal> TOTAL_SHIPPING { get; set; }
        public Nullable<decimal> TOTAL_PRODUCT { get; set; }
        public Nullable<decimal> TOTAL_DEFECT { get; set; }
        public Nullable<decimal> TOTAL_LACKED { get; set; }
        public Nullable<decimal> TOTAL_EXCESSIVE { get; set; }
        public Nullable<decimal> TOTAL_PO { get; set; }
        public Nullable<decimal> TOTAL_STOCK_IN { get; set; }
        public Nullable<decimal> TM_ORDER { get; set; }
        public Nullable<decimal> TM_DELIVERY { get; set; }
        public Nullable<decimal> TM_PRODUCT { get; set; }
        public Nullable<decimal> TM_DEFECT { get; set; }
        public Nullable<decimal> TM_LACKED { get; set; }
        public Nullable<decimal> TM_EXCESSIVE { get; set; }
        public Nullable<decimal> TM_PO { get; set; }
        public Nullable<decimal> TM_STOCK_IN { get; set; }
        public Nullable<decimal> LM_STOCK { get; set; }
        public Nullable<decimal> L2M_STOCK { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string INPUT_PERSON { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFY_PERSON { get; set; }
        public string DELTA_NO { get; set; }
        public string SHIP_TYPE { get; set; }
        public string PATH_BOX { get; set; }
        public string IVPART_NAME { get; set; }
        public string PROLINE_CODE { get; set; }
        public string PROCESS_CODE { get; set; }
        public Nullable<decimal> PALLET_WEIGHT { get; set; }
        public Nullable<decimal> BOXPERPALLET_QTY { get; set; }
        public bool DEL_FLAG { get; set; }
        public Nullable<decimal> TOLERANCE { get; set; }
        public string CUS_ITEM_NAME { get; set; }
        public string ACC_ITEM_CODE { get; set; }
    }
}
