//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKAKO_ERP_3LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPRICE_GLOBALMF
    {
        public string PRICE_CODE { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string GLOBAL_CODE { get; set; }
        public string GLOBAL_NAME { get; set; }
        public string TESTMASS { get; set; }
        public System.DateTime APPLYDATE { get; set; }
        public decimal PRICE { get; set; }
        public string PRICE_UNIT { get; set; }
        public string PAYMENT_TERM { get; set; }
        public string INCO_TERM { get; set; }
        public string REASON_CODE { get; set; }
        public string REFERENCE { get; set; }
        public string INV_DV { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string INPUT_PERSON { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFY_PERSON { get; set; }
    }
}
