//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKAKO_ERP_3LAYER
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Takako_Entities : DbContext
    {
        public Takako_Entities()
            : base("name=Takako_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TVC_COMPANY_MS> TVC_COMPANY_MS { get; set; }
        public DbSet<TVC_CUSTOMER_MS> TVC_CUSTOMER_MS { get; set; }
        public DbSet<TVC_ERROR_LOG> TVC_ERROR_LOG { get; set; }
        public DbSet<TVC_HANDLE_LOG> TVC_HANDLE_LOG { get; set; }
        public DbSet<TVC_INV_DETAIL> TVC_INV_DETAIL { get; set; }
        public DbSet<TVC_INV_MS> TVC_INV_MS { get; set; }
        public DbSet<TVC_LOG_SCREEN> TVC_LOG_SCREEN { get; set; }
        public DbSet<TVC_PO_MS> TVC_PO_MS { get; set; }
        public DbSet<TVC_PO_MS_BK> TVC_PO_MS_BK { get; set; }
        public DbSet<TVC_SHIPPING_INV_DETAIL> TVC_SHIPPING_INV_DETAIL { get; set; }
        public DbSet<TVC_SHIPPING_MS> TVC_SHIPPING_MS { get; set; }
        public DbSet<TVC_SHIPPING_PL_DETAIL> TVC_SHIPPING_PL_DETAIL { get; set; }
        public DbSet<TVC_USER_MS> TVC_USER_MS { get; set; }
        public DbSet<TVC_PL_DETAIL> TVC_PL_DETAIL { get; set; }
    
        public virtual int SP_TVC_DELETE_INV(string invoiceNo)
        {
            var invoiceNoParameter = invoiceNo != null ?
                new ObjectParameter("InvoiceNo", invoiceNo) :
                new ObjectParameter("InvoiceNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TVC_DELETE_INV", invoiceNoParameter);
        }
    
        public virtual int SP_TVC_EXPORT_ACTUAL_PRODUCT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TVC_EXPORT_ACTUAL_PRODUCT");
        }
    
        public virtual int SP_TVC_INSERT_PO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TVC_INSERT_PO");
        }
    
        public virtual int SP_TVC_LOCK_INV(string invoiceNo)
        {
            var invoiceNoParameter = invoiceNo != null ?
                new ObjectParameter("InvoiceNo", invoiceNo) :
                new ObjectParameter("InvoiceNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TVC_LOCK_INV", invoiceNoParameter);
        }
    
        public virtual int SP_TVC_LOCK_SHIPPING_INSTRUCTION(string shippingNo)
        {
            var shippingNoParameter = shippingNo != null ?
                new ObjectParameter("ShippingNo", shippingNo) :
                new ObjectParameter("ShippingNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TVC_LOCK_SHIPPING_INSTRUCTION", shippingNoParameter);
        }
    
        public virtual int SP_TVC_MERGE_DATA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TVC_MERGE_DATA");
        }
    
        public virtual int SP_TVC_REVISE_SHIPPING_INSTRUCTION(string shippingNo)
        {
            var shippingNoParameter = shippingNo != null ?
                new ObjectParameter("ShippingNo", shippingNo) :
                new ObjectParameter("ShippingNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TVC_REVISE_SHIPPING_INSTRUCTION", shippingNoParameter);
        }
    
        public virtual int SP_TVC_SELECT_INV_BY_SHIPNO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TVC_SELECT_INV_BY_SHIPNO");
        }
    
        public virtual int SP_TVC_SELECT_PL_BY_SHIPNO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TVC_SELECT_PL_BY_SHIPNO");
        }
    
        public virtual int SP_TVC_UNLOCK_SHIPPING_INSTRUCTION(string shippingNo)
        {
            var shippingNoParameter = shippingNo != null ?
                new ObjectParameter("ShippingNo", shippingNo) :
                new ObjectParameter("ShippingNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TVC_UNLOCK_SHIPPING_INSTRUCTION", shippingNoParameter);
        }
    
        public virtual int SP_TVC_UPDATE_INV_NORMAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TVC_UPDATE_INV_NORMAL");
        }
    
        public virtual int SP_TVC_UPDATE_SHIPPING_NORMAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TVC_UPDATE_SHIPPING_NORMAL");
        }
    }
}
