//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKAKO_ERP_3LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVC_PL_DETAIL
    {
        public long PL_DETAIL_NUM { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string SHIPPING_NO { get; set; }
        public string INVOICE_NO { get; set; }
        public string REVISE_NO { get; set; }
        public Nullable<System.DateTime> REVISE_DATE { get; set; }
        public int REVISE_VERSION { get; set; }
        public string PACKAGES_NO { get; set; }
        public string TVC_ITEM_CODE { get; set; }
        public string CUSTOMER_PO { get; set; }
        public decimal QTY_CARTON { get; set; }
        public decimal QTY_PER_CARTON { get; set; }
        public decimal QTY_TOTAL { get; set; }
        public decimal QTY_TOTAL_REVISE { get; set; }
        public decimal NET_WEIGHT { get; set; }
        public Nullable<decimal> NET_WEIGHT_TOTAL { get; set; }
        public decimal GROSS_WEIGHT { get; set; }
        public string LOT_NO { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> EDIT_AT { get; set; }
    }
}
