//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKAKO_ERP_3LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVC_PO_MS
    {
        public long PO_NUM { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string RECEIVE_NO { get; set; }
        public string INVOICE_NO { get; set; }
        public string SHIPPING_NO { get; set; }
        public string TVC_ITEM_CODE { get; set; }
        public string CUSTOMER_ITEM_CODE { get; set; }
        public string PARTS_NAME { get; set; }
        public string ITEM_NAME { get; set; }
        public int QUANTITY { get; set; }
        public Nullable<int> QUANTITY_ORDER { get; set; }
        public string UNIT_CURRENCY { get; set; }
        public decimal PRICE_JPY { get; set; }
        public decimal PRICE_USD { get; set; }
        public string CUSTOMER_PO { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public System.DateTime DUE_DATE { get; set; }
        public string THIRD_PARTY_ITEM_CODE { get; set; }
        public string THIRD_PARTY_PO { get; set; }
        public string NOTE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> EDIT_AT { get; set; }
    }
}
