//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKAKO_ERP_3LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVC_INV_MS
    {
        public long INV_NUM { get; set; }
        public int LOCK_STATUS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string SHIPPING_NO { get; set; }
        public string INVOICE_NO { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public string ISSUEDTO_CUSTOMER_CODE { get; set; }
        public string ISSUEDTO_CUSTOMER_NAME { get; set; }
        public string ISSUEDTO_CUSTOMER_ADDRESS { get; set; }
        public string ISSUEDTO_CUSTOMER_TEL_NO { get; set; }
        public string ISSUEDTO_CUSTOMER_FAX_NO { get; set; }
        public string SHIPTO_CUSTOMER_CODE { get; set; }
        public string SHIPTO_CUSTOMER_NAME { get; set; }
        public string SHIPTO_CUSTOMER_ADDRESS { get; set; }
        public string SHIPTO_CUSTOMER_TEL_NO { get; set; }
        public string SHIPTO_CUSTOMER_FAX_NO { get; set; }
        public string REVENUE { get; set; }
        public string SHIP_VIA { get; set; }
        public int FREIGHT { get; set; }
        public string VESSEL { get; set; }
        public string PORT_OF_LOADING { get; set; }
        public string PORT_OF_DESTINATION { get; set; }
        public System.DateTime ETD { get; set; }
        public System.DateTime ETA { get; set; }
        public string TRADE_CONDITION { get; set; }
        public string PAYMENT_TERM { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> EDIT_AT { get; set; }
    }
}
