//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKAKO_ERP_3LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVC_HANDLE_LOG
    {
        public long HANDLE_LOG_NUM { get; set; }
        public string COMPANY_CODE { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<System.DateTime> DATE_CREATE { get; set; }
        public string TYPE { get; set; }
        public string CONTENT_LOG { get; set; }
    }
}
