//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKAKO_ERP_3LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVC_INV_DETAIL
    {
        public long INV_DETAIL_NUM { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string SHIPPING_NO { get; set; }
        public string INVOICE_NO { get; set; }
        public string REVISE_NO { get; set; }
        public Nullable<System.DateTime> REVISE_DATE { get; set; }
        public int REVISE_VERSION { get; set; }
        public string PART_DESCRIPTION { get; set; }
        public string CUS_ITEM_CODE { get; set; }
        public string TVC_ITEM_CODE { get; set; }
        public string CUSTOMER_PO { get; set; }
        public string THIRD_PARTY_ITEM_CODE { get; set; }
        public string THIRD_PARTY_PO { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public System.DateTime DUE_DATE_PO { get; set; }
        public decimal QUANTITY { get; set; }
        public decimal QUANTITY_REVISE { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public string UNIT_CURRENCY { get; set; }
        public Nullable<decimal> USD_RATE { get; set; }
        public decimal ORDER_PRICE { get; set; }
        public decimal ORDER_PRICE_REVISE { get; set; }
        public Nullable<decimal> GLOBAL_PRICE { get; set; }
        public decimal AMOUNT { get; set; }
        public string NOTE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> EDIT_AT { get; set; }
    }
}
