//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKAKO_ERP_3LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVC_CUSTOMER_MS
    {
        public long CUSTOMER_NUM { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string TVC_ITEM_CODE { get; set; }
        public string SHIP_TO { get; set; }
        public string UNIT_CURRENCY { get; set; }
        public string THIRD_PARTY_CODE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> EDIT_AT { get; set; }
    }
}
