//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKAKO_ERP_3LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVC_ERROR_LOG
    {
        public long ERROR_LOG_NUM { get; set; }
        public string COMPANY_CODE { get; set; }
        public string USER_NAME { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public string TYPE { get; set; }
        public string SCREEN_LOG { get; set; }
        public string CONTENT { get; set; }
    }
}
